language: node_js
node_js:
  - 11
  - 10
before_script:
  - yarn install
script:
  - yarn run lint
  - yarn run test:coverage:coveralls
before_deploy:
  - tar -zcf ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz .
  - zip -qr ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.zip . -x *.git* coverage/\* node_modules/\*
notifications:
  slack: theselftalk:EHiDWYYgq34Y172TrHTqA16W
deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_TOKEN"
    on:
      branch: master
      tags: true
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true
